version: '3.8'

services:
  postgres:
    container_name: postgres-sql-frm
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-frm
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-demo
    restart: unless-stopped

  spring-backend:
    container_name: spring-backend-frm
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PW}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - spring-demo
    restart: unless-stopped

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
